### ISSUE TITLE
Define sanitizeHtml on client side

### ISSUE THREAD

**Issue by petermikitsh** [djedi23/meteor-sanitize-html#4]
It would be convenient to have the sanitizeHtml global variable defined on the client as well. It would make integration with autoform simpler, e.g., this

```
    autoValue: function () {
      if (this.isSet) {
        return Meteor.isServer ? sanitizeHtml(this.value) : this.value;
      }
    }
```

becomes this:

```
    autoValue: function () {
      if (this.isSet) {
        return sanitizeHtml(this.value);
      }
    }
```

Thanks!

**Comment by djedi23** [comment]
You can define a function like these in your `client/lib`:

``` js
// imply if (Meteor.isClient()) {
sanitizeHtml = function sanitizeHtml(value) {
  return value;
}
// }
```

but i don't think i can include it in the package because I don't know the all the use cases: here you need to return the `identity`, others may need to return `null` or to throws an error.

**Comment by petermikitsh** [comment]
Ah yeah, I see that it's a pain to use Npm modules client side. I wonder how other packages do it, like momentjs. For now, however, this will do. Thanks!

**Comment by SachaG** [comment]
Yeah, it'd be great to have the same APIs on the client. I'm guessing that might require getting rid of the dependency on the NPM package though…
